# -*- coding: utf-8 -*-
"""enem_microdados_por_estado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihwqb-LiGYA3x5U_ABp_Rb-CfVdxbJ4X

# Carregando dados
### Utilizando dataset do ENEM 2019
### Baixando via API do Kaggle
"""

!pip install kaggle

!mkdir -p ~/.kaggle
!cp /content/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kaggle

"""dicionario dos dados = https://edisciplinas.usp.br/mod/resource/view.php?id=3597672

yt = https://www.youtube.com/watch?v=Gn6Fm3iDbd8&list=PL5TJqBvpXQv5N3iV68bGBkea0HjMk98lR&index=3
"""

kaggle.api.authenticate()
kaggle.api.dataset_download_files('asneto/microdados-enem-2019-por-estado', unzip=True, path="/content/")

df = pd.read_csv("/content/Selec_SC.txt", sep=";")
df.head(10)

"""# Filtrando colunas desejadas"""

features= ["ID","TP_SEXO","NU_IDADE", "TP_COR_RACA", "NO_MUNICIPIO_RESIDENCIA", "TP_ESCOLA", "NU_NOTA_CN","NU_NOTA_CH","NU_NOTA_LC","NU_NOTA_MT","NU_NOTA_REDACAO", "TP_LINGUA",
           "Q001","Q002","Q005","Q006", "Q025 "]

df.info()
df.describe()

"""# Filtrando"""

(df["NO_MUNICIPIO_RESIDENCIA"] == "Araranguá").value_counts()

# porcantagem de provas aplicadas em aru em relacao ao total de sc
proporcao = (df["NO_MUNICIPIO_RESIDENCIA"] == "Araranguá").value_counts()
print((proporcao[1]/proporcao.sum())*100)
print((proporcao[0]/proporcao.sum())*100)
# aru < 1%

df_aru = df[df["NO_MUNICIPIO_RESIDENCIA"] == "Araranguá"]
df_aru.head()

""" # Análise de araranguá"""

#grafico da distribuição das idades na prova enem 2019 - ararangua

sns.countplot(x="NU_IDADE", data=df_aru, width=0.3)  # Ajuste o valor de 'width' para controlar a largura da barra
plt.xticks(rotation=60, ha="right")
plt.tight_layout()
plt.show()

#grafico da distribuição dos generos na prova enem 2019 - ararangua

palette = sns.color_palette("husl", len(df_aru["TP_SEXO"].unique()))
sns.countplot(x="TP_SEXO", data=df_aru, width=0.3, palette=palette)
plt.xticks( ha="right")
plt.tight_layout()
plt.show()

df_aru["TESTS_GRADE"] = (df_aru["NU_NOTA_CN"] + df_aru["NU_NOTA_CH"] + df_aru["NU_NOTA_LC"] + df_aru["NU_NOTA_MT"])/5

df_aru["TESTS_GRADE"].head()

#df_aru = df_aru.reset_index()

# histograma com a distribuiçao das notas na cidade de ararangua

sns.histplot(data=df_aru, x="TESTS_GRADE", kde=True)

plt.tight_layout()
plt.show()

df_aru